apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-alloc-server-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: stocks-alloc-server
          image: jawny/stocks-alloc-server:1.0
          ports:
            - containerPort: 5000
